### ISSUE TITLE
Comparison with honnef.co/go/unused?

### ISSUE THREAD

**Issue by dmitshur** [mdempsky/codesweep#3]
I just discovered this, and on the surface this looks a lot like [`honnef.co/go/unused/cmd/unused`](https://github.com/dominikh/go-unused#readme).

I'd like to inquire, how does `codesweep` compare to/differ from that tool?

/cc @dominikh @dgryski

**Comment by mdempsky** [comment]
It's entirely possible unused already does what I want. The main feature we needed in the compiler was to recognize external symbols that aren't used across package boundaries.

**Comment by mdempsky** [comment]
It looks like unused's -exported flag may do what I want.

**Comment by mdempsky** [comment]
It does! I think codesweep's current functionality may be redundant then.

**Comment by dmitshur** [comment]
This question has been answered, so I'll close the issue. Thanks.
