### ISSUE TITLE
Names in function and interface signatures

### ISSUE THREAD

**Issue by madelynnblue** [mdempsky/codesweep#4]
`func f(i int) (r int) { return 0}`

will complain about `i`, which is arguably reasonable, although often annoying. It will also complain about `r`, as a named return. These should probably be ignored or a flag added for them since sometimes the names are there as part of docs, but the vars are never referenced.

Similarly, in interface specs:

```
type i interface {
  f(n int)
}
```

`n` will be flagged as unused, which is almost certainly unwanted.

**Comment by mdempsky** [comment]
Yeah, I was noticing this too.  Definitely not intentional, and something I'd like to fix.
